name: AdvancedBroadcasts
version: '${project.version}'
main: xyz.carpodi.advancedbroadcasts.AdvancedBroadcasts
api-version: 1.19
authors: [ Carpodi ]
description: This plugin makes your server broadcasts/announcements more custom!
website: https://github.com/carpodi
commands:
  broadcast:
    usage: /broadcast <message>
    aliases: [bc, advancedbroadcast, ]
